ai_cctv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('camera/', include('camera.urls')),
    path('', main, name='dashboards'),
    path('list/', video_list, name='video_list'),
    path('users/', include('users.urls')),
    path('profile', profile, name='profile'),
    path('', include('pwa.urls')),

    path('token_save/',token_save,name="token_save"),
    path('token_delete/',token_delete,name="token_delete"),
    path('firebase-messaging-sw.js', firebase_messaging_sw,name='firebase_messaging_sw'),
    # firebase cloud message
    # path("firebase-messaging-sw.js",
    #      TemplateView.as_view(
    #          template_name="firebase-messaging-sw.js",
    #          content_type="application/javascript",
    #      ),
    #      name="firebase-messaging-sw"
    #      ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import *
from django.urls import path

app_name = "users"

urlpatterns = [
    path('kakao_login', kakao_login, name="kakao_login"),
    path('kakao/login/callback/', get_token, name="get_token"),

    # path('profile_update',profile_update,name="profile_update"),
    path('kakao_logout', kakao_logout, name="kakao_logout"),

    # django 로그아웃
    path('logout', service_logout, name="logout"),
    path('kakao/logout/callback/', go_main, name="go_main"),


    path('profile_update_page', profile_update_page, name="profile_update_page"),
    path('profile_update', profile_update, name="profile_update"),

    # path('create_store_page', create_store_page, name="create_store_page"),
    path('create_store', create_store, name="create_store"),
    # path('update_store_page/<str:store_id>',update_store_page, name="update_store_page"),
    path('update_store/<str:store_id>', update_store, name="update_store"),
    path('delete_store/<str:store_id>', delete_store, name="delete_store"),
    path('set_main_store/<str:store_id>', set_main_store, name="set_main_store"),


    path('show_store_list', show_store_list, name="show_store_list"),
    # path('show_store_info/<str:store_id>',show_store_info, name="show_store_info"),
    path('create_camera/<str:store_id>', create_camera, name="create_camera"),
    # path('update_camera_page/<str:store_id>/<str:camera_id>', update_camera_page, name="update_camera_page"),
    path('update_camera/<str:store_id>/<str:camera_id>', update_camera, name="update_camera"),
    path('delete_camera/<str:store_id>/<str:camera_id>', delete_camera, name="delete_camera"),
    path('set_default_camera/<str:store_id>/<str:camera_id>', set_default_camera, name="set_default_camera"),
    
    path('want_push', want_push, name="want_push"),
]

ai_cctv/views.py
from django.contrib.auth.decorators import login_required
from fcm_django.models import FCMDevice
from firebase_admin.messaging import Message
from .push_fcm_notification import send_to_firebase_cloud_messaging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .push_fcm_notification import send_to_firebase_cloud_messaging
from django.contrib import messages
from firebase_admin.messaging import Message
from fcm_django.models import FCMDevice
from time import sleep
from users.models import *
from camera.models import *
from django.db.models import Q, Count
from django.utils import timezone
import datetime
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json

def main(request):
    try:
        # 알람 설정하기
        # alarm_state = False

        today = timezone.now().date()
        tomorrow = today+datetime.timedelta(days=1)
        main_store = request.user.profile.main_store

        main_store_cameras = Camera.objects.filter(store=main_store)
        if main_store:
            # 전체 매장 - 드롭다운용
            stores = Store.objects.filter(
                owner=request.user).exclude(id=main_store.id)
            print(stores)

            daily_cumulative_detection=0
            
            for camera in main_store_cameras:
                
                #한 카메라에 대한 하루 비디오 정보
                videos=Video.objects.filter( 
                                Q(datetime__gte=today)&Q(datetime__lte=tomorrow)& Q(camera=camera))
                
                daily_cumulative_detection+=videos.count()
     
            context={
                "main_store":main_store,
                "stores":stores,
                "daily_cumulative_detection":daily_cumulative_detection
            }



        return render(request, 'main.html', {"context": context})
    except:
        return render(request, 'main.html')


@login_required(login_url='dashboards')
def video_list(request):
    try:
        today = timezone.now().date()
        tomorrow = today+datetime.timedelta(days=1)
        main_store = request.user.profile.main_store
        main_store_cameras = Camera.objects.filter(store=main_store)
        if main_store:
            # 전체 매장 - 드롭다운용
            stores = Store.objects.filter(
                owner=request.user).exclude(id=main_store.id)

            video_l = []
            for camera in main_store_cameras:

                if request.GET:
                    start_date = datetime.datetime.strptime(
                        request.GET['start'], '%m/%d/%Y')
                    end_date = datetime.datetime.strptime(
                        request.GET['end'], '%m/%d/%Y')
                    videos = Video.objects.filter(Q(datetime__lte=end_date) & Q(
                        datetime__gte=start_date) & Q(camera=camera)).order_by('-datetime')
                else:
                    # 한 카메라에 대한 하루 비디오 정보
                    videos = Video.objects.filter(
                        Q(datetime__gte=today) & Q(datetime__lte=tomorrow) & Q(camera=camera)).order_by('-datetime')
                for i in videos:
                    video_path = '/'.join(i.video.split('/')[-4:])
                    video_path = os.path.join('../../', video_path)
                    i.video = video_path

                    image_path = '/'.join(i.thumbnail.split('/')[-4:])
                    image_path = os.path.join('../../', image_path)
                    i.thumbnail = image_path
                video_l.append(videos)
            print(video_l)
            context = {
                "stores": stores,
                "video_list": video_l,
                "main_store": main_store
            }
            return render(request, 'video_list.html', {"context": context})
        else:
            print('메인 매장이없음')
            messages.warning(request, "메인 매장이 없습니다. 설정하세요")
            return redirect('dashboards')
    except:
        return render(request,'video_list.html')

@login_required(login_url='dashboards')
def profile(request):
    return render(request, 'profile.html')


def firebase_messaging_sw(request):
    return render(request, 'firebase-messaging-sw.js'
    ,content_type="application/javascript")


@require_POST
def token_save(request):
    request.user.profile.fcm_token=request.POST['registration_id']
    request.user.profile.save()
    return HttpResponse(json.dumps({"user_nickname":request.user.profile.username}),content_type="application/json")

@require_POST
def token_delete(request):
    request.user.profile.fcm_token=None
    request.user.profile.save()
    return HttpResponse(json.dumps({"user_nickname":request.user.profile.username}),content_type="application/json")

ai_cctv/templates/partials/header.html
{% load static %}
<header
  class="flex items-center justify-between lg:justify-end w-full px-4 h-14 bg-white"
>
  <button
    class="block btn hover:btn-light-secondary md:hihidden lg:hidden"
    @click.stop="sideBar = true"
  >
    <span class="sr-only">Menu</span>
    <svg
      class="w-4 h-4"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path
        fill-rule="evenodd"
        d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
        clip-rule="evenodd"
      />
    </svg>
    
  </button>

  <div class="flex items-center">

    <div class="flex items-center mr-2 md:order-2">
      <button
        type="button"
        class="flex ml-3 text-sm border-2 border-primary-light rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600"
        id="user-menu-button"
        aria-expanded="false"
        data-dropdown-toggle="user-dropdown"
        data-dropdown-placement="bottom"
      >
        <span class="sr-only">Open user menu</span>
        {% if request.user.is_authenticated %}
        <img
          class="w-8 h-8 rounded-full"
          {% if request.user.profile.photo %}
            src="{{request.user.profile.photo.url}}"
          {% else %}
            src="{% static 'images/placeholder.jpeg' %}"
          {% endif %}
          alt="user photo"
        />
        {% else %}
        <img
          class="w-8 h-8 rounded-full"
          src="{% static 'images/placeholder.jpeg' %}"
          alt="user photo"
        />
        {% endif %}
      </button>
      <!-- Dropdown menu -->
      <div
        class="mr-5 hidden z-50 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600"
        id="user-dropdown"
        data-popper-reference-hidden=""
        data-popper-escaped=""
        data-popper-placement="bottom"
        style="
          position: absolute;
          inset: 0px auto auto 0px;
          margin: 0px;
          transform: translate3d(0px, 758px, 0px);
        "
      >
        <div class="py-3 px-4">
          {% if request.user.is_authenticated %}

          <span class="block text-sm text-gray-900 dark:text-white"
            >{{request.user.profile.username}}</span
          >
          {% else %}
          {%endif%}
          {% comment %}
          <span
            class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400"
            >name@flowbite.com</span
          >
          {% endcomment %}
        </div>
        <ul class="py-1" aria-labelledby="user-menu-button">
          {% if request.user.is_authenticated %}
          <li>
            <a
              href="{% url 'users:logout' %}"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Log Out</a>
          </li>
          <li>
            <a
              href="{% url 'profile'%}"
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              >Profile</a
            >
          </li>
          {% else %}
          <li>
            <button
              class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white"
              data-modal-toggle="popup-modal-login"
              >Log In</button
            >
          </li>
          {%endif%}
          
        </ul>
      </div>
    </div>
  </div>
</header>

<!-- modal to log in -->
<!-- add get nickname, profile image, store name, store address(format?) -->
<div
  id="popup-modal-login"
  tabindex="-1"
  class="hidden overflow-y-auto overflow-x-hidden fixed top-1/3 right-0 left-0 z-50 md:inset-0 h-modal md:h-full"
>
  <div class="relative p-4 w-full max-w-md h-full md:h-auto">
    <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
      <button
        type="button"
        class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white"
        data-modal-toggle="popup-modal-login"
      >
        <svg
          aria-hidden="true"
          class="w-5 h-5"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <span class="sr-only">Close modal</span>
      </button>
      <div class="p-6 text-center">
        <a
          href="{% url 'users:kakao_login' %}"
          class=""
        >
          <img
            class=""
            src="{% static 'images/kakao_login_large_wide.png' %}"
            alt="user photo"
          />
        </a>
      </div>
    </div>
  </div>
</div>

ai_cctv/templates/partials/list_box.html
{% load static %}

<div>
  <button type="button" data-modal-toggle="popup-modal">
    <img src="{{thumbnail}}" class="object-cover w-full h-56 bg-center rounded" alt="thumbnail" loading="lazy" />
  </button>
  <h2 class="mb-2 text-lg font-semibold text-gray-900">
    <p data-modal-toggle="popup-modal" class="text-gray-900 hover:text-purple-700">{{type}} 감지</p>
  </h2>
  <p class="mb-3 text-sm font-normal text-gray-500">
    <span id="rtsp_value" style="display:block" class="overflow-auto w-full">카메라</span>
    <span id="rtsp_value" style="display:block" class="overflow-auto w-full">{{camera.rtsp_url}}</span>
  </p>
  <p class="mb-3 text-sm font-normal text-gray-500">
    <p class="mb-3 text-sm font-normal text-gray-500 ">매장명 :{{camera.store.name}}</p>
    <p class="mb-3 text-sm font-normal text-gray-500 "> <a class="font-medium text-gray-900 hover:text-purple-700">{{datetime}} </a></p>
  </p>
</div>




<!-- modal -->
<div id="popup-modal" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 md:inset-0 h-modal md:h-full justify-center items-center" aria-hidden="true">
  <div class="relative p-4 w-full h-full max-w-2xl ">
      <div class="relative w-full h-auto bg-white rounded-lg shadow dark:bg-gray-700 flex flex-col items-center">
          <button type="button" class="absolute top-1 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-toggle="popup-modal">
              <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
              <span class="sr-only">Close modal</span>
          </button>
          <video controls width='100%' height='100%' class="mt-10">
              <source src='{{video}}' type="video/mp4"></source>
              {% comment %} <source src='{% static "images/test.mp4" %}' type="video/mp4"></source> {% endcomment %}
          </video> 
      </div>
  </div>
</div>

ai_cctv/templates/partials/nav.html
<!-- Side bar-->
<div
  id="sidebar"
  class="h-screen w-16 menu bg-white text-white px-4 flex items-center nunito static fixed shadow"
>
  <ul class="list-reset">
    <li class="my-2 md:my-0">
      <a
        href="#"
        class="block py-1 md:py-3 pl-1 align-middle text-gray-600 no-underline hover:text-indigo-400"
      >
        <i class="fas fa-home fa-fw mr-3"></i
        ><span class="w-full inline-block pb-1 md:pb-0 text-sm">Home</span>
      </a>
    </li>
    <li class="my-2 md:my-0">
      <a
        href="#"
        class="block py-1 md:py-3 pl-1 align-middle text-gray-600 no-underline hover:text-indigo-400"
      >
        <i class="fas fa-tasks fa-fw mr-3"></i
        ><span class="w-full inline-block pb-1 md:pb-0 text-sm">Tasks</span>
      </a>
    </li>
    <li class="my-2 md:my-0">
      <a
        href="#"
        class="block py-1 md:py-3 pl-1 align-middle text-gray-600 no-underline hover:text-indigo-400"
      >
        <i class="fa fa-envelope fa-fw mr-3"></i
        ><span class="w-full inline-block pb-1 md:pb-0 text-sm">Messages</span>
      </a>
    </li>
    <li class="my-2 md:my-0">
      <a
        href="#"
        class="block py-1 md:py-3 pl-1 align-middle text-gray-600 no-underline hover:text-indigo-400"
      >
        <i class="fas fa-chart-area fa-fw mr-3 text-indigo-400"></i
        ><span class="w-full inline-block pb-1 md:pb-0 text-sm">Analytics</span>
      </a>
    </li>
    <li class="my-2 md:my-0">
      <a
        href="#"
        class="block py-1 md:py-3 pl-1 align-middle text-gray-600 no-underline hover:text-indigo-400"
      >
        <i class="fa fa-wallet fa-fw mr-3"></i
        ><span class="w-full inline-block pb-1 md:pb-0 text-sm">Payments</span>
      </a>
    </li>
  </ul>
</div>

ai_cctv/templates/partials/navbar.html
{% load static %}
<nav
  class="fixed top-0 left-0 z-20 h-full pb-10 overflow-x-hidden overflow-y-auto transition origin-left transform bg-white border-r w-60 md:translate-x-0"
  :class="{ '-translate-x-full' : !sideBar, 'translate-x-0' : sideBar }"
  @click.away="sideBar = false"
>
  <a href="/" class="flex items-center  px-4 py-5">
    <img src="{% static 'images/logo.png' %}" alt="Logo" class="w-10" />
    <p class="ml-1 font-mono font-black	text-xl text-primary-dark">대신보다</p>
  </a>
  <nav class="text-sm font-medium text-gray-600" aria-label="Main Navigation">
    <!-- HOME MENU -->
    <a
      class="flex items-center px-4 py-3 transition cursor-pointer group {% if request.path == '/' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} hover:bg-gray-100 hover:text-gray-900 {% endif %}"
      href="/"
    >
      <svg
        class="shrink-0 w-5 h-5 mr-2 transition {% if request.path == '/' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} text-gray-400  group-hover:text-gray-600 {% endif %}"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z"
        />
      </svg>
      <span>Home</span>
    </a>

    <!-- Stores -->
    <a
      class="flex items-center px-4 py-3 transition cursor-pointer group {% if request.path == '/users/show_store_list' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} hover:bg-gray-100 hover:text-gray-900 {% endif %}"
      href="{% url 'users:show_store_list'%}"
    >
    <i class="fa-solid fa-store shrink-0 w-5 h-5 mt-1 mr-2 transition {% if request.path == '/users/show_store_list' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} text-gray-400  group-hover:text-gray-600 {% endif %}">
      <path
        fill-rule="evenodd"
        d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
        clip-rule="evenodd"
      />
    </i>
      <span>Stores</span>
    </a>

    <!-- Collections MENU -->
    <a
      class="flex items-center px-4 py-3 transition cursor-pointer group {% if request.path == '/list/' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} hover:bg-gray-100 hover:text-gray-900 {% endif %}"
      href="/list"
    >
      <svg
        class="shrink-0 w-5 h-5 mr-2 transition {% if request.path == '/list/' %} text-gray-900 bg-gray-100 hover:bg-gray-100 hover:text-gray-900 {% else %} text-gray-400  group-hover:text-gray-600 {% endif %}"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          d="M7 3a1 1 0 000 2h6a1 1 0 100-2H7zM4 7a1 1 0 011-1h10a1 1 0 110 2H5a1 1 0 01-1-1zM2 11a2 2 0 012-2h12a2 2 0 012 2v4a2 2 0 01-2 2H4a2 2 0 01-2-2v-4z"
        />
      </svg>
      <span>Collections</span>
    </a>

  </nav>
</nav>