ai_cctv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('camera/', include('camera.urls')),
    path('', main, name='dashboards'),
    path('list/', video_list, name='video_list'),
    path('users/', include('users.urls')),
    path('profile', profile, name='profile'),
    path('', include('pwa.urls')),

    path('token_save/',token_save,name="token_save"),
    path('token_delete/',token_delete,name="token_delete"),
    path('firebase-messaging-sw.js', firebase_messaging_sw,name='firebase_messaging_sw'),
    # firebase cloud message
    # path("firebase-messaging-sw.js",
    #      TemplateView.as_view(
    #          template_name="firebase-messaging-sw.js",
    #          content_type="application/javascript",
    #      ),
    #      name="firebase-messaging-sw"
    #      ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from .views import *
from django.urls import path

app_name = "users"

urlpatterns = [
    path('kakao_login', kakao_login, name="kakao_login"),
    path('kakao/login/callback/', get_token, name="get_token"),

    # path('profile_update',profile_update,name="profile_update"),
    path('kakao_logout', kakao_logout, name="kakao_logout"),

    # django 로그아웃
    path('logout', service_logout, name="logout"),
    path('kakao/logout/callback/', go_main, name="go_main"),


    path('profile_update_page', profile_update_page, name="profile_update_page"),
    path('profile_update', profile_update, name="profile_update"),

    # path('create_store_page', create_store_page, name="create_store_page"),
    path('create_store', create_store, name="create_store"),
    # path('update_store_page/<str:store_id>',update_store_page, name="update_store_page"),
    path('update_store/<str:store_id>', update_store, name="update_store"),
    path('delete_store/<str:store_id>', delete_store, name="delete_store"),
    path('set_main_store/<str:store_id>', set_main_store, name="set_main_store"),


    path('show_store_list', show_store_list, name="show_store_list"),
    # path('show_store_info/<str:store_id>',show_store_info, name="show_store_info"),
    path('create_camera/<str:store_id>', create_camera, name="create_camera"),
    # path('update_camera_page/<str:store_id>/<str:camera_id>', update_camera_page, name="update_camera_page"),
    path('update_camera/<str:store_id>/<str:camera_id>', update_camera, name="update_camera"),
    path('delete_camera/<str:store_id>/<str:camera_id>', delete_camera, name="delete_camera"),
    path('set_default_camera/<str:store_id>/<str:camera_id>', set_default_camera, name="set_default_camera"),
    
    path('want_push', want_push, name="want_push"),
]

ai_cctv/views.py
from django.contrib.auth.decorators import login_required
from fcm_django.models import FCMDevice
from firebase_admin.messaging import Message
from .push_fcm_notification import send_to_firebase_cloud_messaging
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .push_fcm_notification import send_to_firebase_cloud_messaging
from django.contrib import messages
from firebase_admin.messaging import Message
from fcm_django.models import FCMDevice
from time import sleep
from users.models import *
from camera.models import *
from django.db.models import Q, Count
from django.utils import timezone
import datetime
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json

def main(request):
    try:
        # 알람 설정하기
        # alarm_state = False

        today = timezone.now().date()
        tomorrow = today+datetime.timedelta(days=1)
        main_store = request.user.profile.main_store

        main_store_cameras = Camera.objects.filter(store=main_store)
        if main_store:
            # 전체 매장 - 드롭다운용
            stores = Store.objects.filter(
                owner=request.user).exclude(id=main_store.id)
            print(stores)

            daily_cumulative_detection=0
            
            for camera in main_store_cameras:
                
                #한 카메라에 대한 하루 비디오 정보
                videos=Video.objects.filter( 
                                Q(datetime__gte=today)&Q(datetime__lte=tomorrow)& Q(camera=camera))
                
                daily_cumulative_detection+=videos.count()
     
            context={
                "main_store":main_store,
                "stores":stores,
                "daily_cumulative_detection":daily_cumulative_detection
            }



        return render(request, 'main.html', {"context": context})
    except:
        return render(request, 'main.html')


@login_required(login_url='dashboards')
def video_list(request):
    try:
        today = timezone.now().date()
        tomorrow = today+datetime.timedelta(days=1)
        main_store = request.user.profile.main_store
        main_store_cameras = Camera.objects.filter(store=main_store)
        if main_store:
            # 전체 매장 - 드롭다운용
            stores = Store.objects.filter(
                owner=request.user).exclude(id=main_store.id)

            video_l = []
            for camera in main_store_cameras:

                if request.GET:
                    start_date = datetime.datetime.strptime(
                        request.GET['start'], '%m/%d/%Y')
                    end_date = datetime.datetime.strptime(
                        request.GET['end'], '%m/%d/%Y')
                    videos = Video.objects.filter(Q(datetime__lte=end_date) & Q(
                        datetime__gte=start_date) & Q(camera=camera)).order_by('-datetime')
                else:
                    # 한 카메라에 대한 하루 비디오 정보
                    videos = Video.objects.filter(
                        Q(datetime__gte=today) & Q(datetime__lte=tomorrow) & Q(camera=camera)).order_by('-datetime')
                for i in videos:
                    video_path = '/'.join(i.video.split('/')[-4:])
                    video_path = os.path.join('../../', video_path)
                    i.video = video_path

                    image_path = '/'.join(i.thumbnail.split('/')[-4:])
                    image_path = os.path.join('../../', image_path)
                    i.thumbnail = image_path
                video_l.append(videos)
            print(video_l)
            context = {
                "stores": stores,
                "video_list": video_l,
                "main_store": main_store
            }
            return render(request, 'video_list.html', {"context": context})
        else:
            print('메인 매장이없음')
            messages.warning(request, "메인 매장이 없습니다. 설정하세요")
            return redirect('dashboards')
    except:
        return render(request,'video_list.html')

@login_required(login_url='dashboards')
def profile(request):
    return render(request, 'profile.html')


def firebase_messaging_sw(request):
    return render(request, 'firebase-messaging-sw.js'
    ,content_type="application/javascript")


@require_POST
def token_save(request):
    request.user.profile.fcm_token=request.POST['registration_id']
    request.user.profile.save()
    return HttpResponse(json.dumps({"user_nickname":request.user.profile.username}),content_type="application/json")

@require_POST
def token_delete(request):
    request.user.profile.fcm_token=None
    request.user.profile.save()
    return HttpResponse(json.dumps({"user_nickname":request.user.profile.username}),content_type="application/json")

ai_cctv/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="main-content" class="w-full flex-1">
    <div class="row my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;"/>
    </div>
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}


    <div class="w-full px-4 pt-5 pb-3 mx-auto mt-8 mb-6 bg-white rounded-none shadow-xl sm:rounded-lg sm:w-10/12 md:w-8/12 lg:w-6/12 xl:w-4/12 sm:px-6">
      <h1 class="mb-4 text-lg font-semibold text-left text-gray-900">프로필</h1>
      <form class="mb-8 space-y-4" action="{%url 'users:profile_update'  %}" method ="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="flex justify-between ml-3 my-3 py-3 border-b-2">
          <span class="block text-xs font-medium text-gray-700">Avatar</span>
          <div class="w-full flex justify-center">
            <img class="w-1/2" id="avatar"
            {% if request.user.profile.photo %}
            src="{{request.user.profile.photo.url}}"
            {% else %}
            src="{% static 'images/placeholder.jpeg' %}"
            {% endif %}
            />
          </div>
        </div>
        <div class="flex justify-between ml-3 my-3 py-3">
          <span class="block mb-1 text-xs font-medium text-gray-700">Username</span>
          <div class="w-full flex justify-center">
            <span class="block mb-1 text-4xl font-medium text-gray-700">{{request.user.profile.username}}</span>
          </div>
        </div>
        {% comment %} <label class="block">
          <span class="block mb-1 text-xs font-medium text-gray-700">Email</span>
          <input class="form-input" type="email" placeholder="{{ user_form.email }}" inputmode="email" required="">
        </label> {% endcomment %}
        <a href="/users/profile_update_page" class="w-full py-3 mt-1 btn btn-primary">수정하기</a>
      </form>
    </div>








      {% comment %} <div class="space-y-8">
        <div class="text-center border-b border-gray-200" style="line-height: 0px">
          <span class="p-2 text-xs font-semibold tracking-wide text-gray-600 uppercase bg-white" style="line-height: 0px">Or</span>
        </div>
        <div class="grid grid-cols-2 gap-4">
          <a href="javascript:;" class="py-3 btn btn-icon btn-google">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="mr-1">
              <path d="M20.283,10.356h-8.327v3.451h4.792c-0.446,2.193-2.313,3.453-4.792,3.453c-2.923,0-5.279-2.356-5.279-5.28	c0-2.923,2.356-5.279,5.279-5.279c1.259,0,2.397,0.447,3.29,1.178l2.6-2.599c-1.584-1.381-3.615-2.233-5.89-2.233	c-4.954,0-8.934,3.979-8.934,8.934c0,4.955,3.979,8.934,8.934,8.934c4.467,0,8.529-3.249,8.529-8.934	C20.485,11.453,20.404,10.884,20.283,10.356z"></path>
            </svg>
            <span class="sr-only">Continue with</span> Google
          </a>
          <a href="javascript:;" class="py-3 btn btn-icon btn-dark">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="currentColor" class="mr-1">
              <path d="M19.665,16.811c-0.287,0.664-0.627,1.275-1.021,1.837c-0.537,0.767-0.978,1.297-1.316,1.592	c-0.525,0.482-1.089,0.73-1.692,0.744c-0.432,0-0.954-0.123-1.562-0.373c-0.61-0.249-1.17-0.371-1.683-0.371	c-0.537,0-1.113,0.122-1.73,0.371c-0.616,0.25-1.114,0.381-1.495,0.393c-0.577,0.025-1.154-0.229-1.729-0.764	c-0.367-0.32-0.826-0.87-1.377-1.648c-0.59-0.829-1.075-1.794-1.455-2.891c-0.407-1.187-0.611-2.335-0.611-3.447	c0-1.273,0.275-2.372,0.826-3.292c0.434-0.74,1.01-1.323,1.73-1.751C7.271,6.782,8.051,6.563,8.89,6.549	c0.46,0,1.063,0.142,1.81,0.422s1.227,0.422,1.436,0.422c0.158,0,0.689-0.167,1.593-0.498c0.853-0.307,1.573-0.434,2.163-0.384	c1.6,0.129,2.801,0.759,3.6,1.895c-1.43,0.867-2.137,2.08-2.123,3.637c0.012,1.213,0.453,2.222,1.317,3.023	c0.392,0.372,0.829,0.659,1.315,0.863C19.895,16.236,19.783,16.529,19.665,16.811L19.665,16.811z M15.998,2.38	c0,0.95-0.348,1.838-1.039,2.659c-0.836,0.976-1.846,1.541-2.941,1.452c-0.014-0.114-0.021-0.234-0.021-0.36	c0-0.913,0.396-1.889,1.103-2.688c0.352-0.404,0.8-0.741,1.343-1.009c0.542-0.264,1.054-0.41,1.536-0.435	C15.992,2.127,15.998,2.254,15.998,2.38L15.998,2.38z"></path>
            </svg>
            <span class="sr-only">Continue with</span> Apple
          </a>
        </div>
      </div> {% endcomment %}




    {% comment %} <div class="form-content">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="form-row">
                <div class="col-md-5">
                    <div class="form-group">
                        <label class="small mb-1">Username:</label>
                            {{ user_form.username }}
                        <label class="small mb-1">Email:</label>
                            {{ user_form.email }}
                    </div>
                    <div class="form-group">
                        <a href="#">Change Password</a>
                        <hr>
                        <label class="small mb-1">Change Avatar:</label>
                        {{ profile_form.avatar }}
                    </div>
                    <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                </div>
            </div>
            <br><br>
            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>
            <button type="reset" class="btn btn-dark btn-lg">Reset</button>
        </form>
    </div>
</div> {% endcomment %}
{% endblock content %}

ai_cctv/templates/video_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class=" mx-auto max-w-7xl">
  <div class="flex flex-col justify-between">
    <div>
      <h1 class="mb-3 text-4xl font-bold leading-tight text-gray-900 md:font-extrabold">감지 영상 목록</h1>
      <p class="mb-6 text-lg text-gray-500 md:text-xl">이상상황으로 판단된 상황의 영상입니다. 아래를 눌러 확인하세요.</p>
    </div>
    <div class="flex flex-col items-end">
      <!-- Drop Down - select store -->
      <div class="dropdown-lg" x-data="dropdown()">
        <button class="btn btn-light-primary btn-lg" id="open-color-menu-large" x-spread="trigger">
          {{context.main_store.name}}
          {% if context.stores %}
            <svg class="dropdown-arrow" :class="{ 'rotate-180': open }" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>
          {%endif%}
        </button>
        {% if context.stores %}
        <div class="dropdown-list" id="color-menu-large" x-spread="dropdown" x-cloak>
          {% for store in context.stores %}
          <a href="{% url 'users:set_main_store' store.id %}" class="dropdown-item">{{store.name}}</a>
          {%endfor%}
        </div>
        {% endif %}
      </div>
      <!-- Date Search Form -->
      <form class="mt-5" action="{% url 'video_list' %}">
        {% csrf_token %}
        <div  class="flex  items-center ">
            <div  date-rangepicker="" class="sm:flex sm:justify-center sm:items-center lg:justify-start">
                <div class="relative">
                    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                    </div>
                    <input   name="start" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 " placeholder="Select date start">
                </div>
                <span class="mx-4 text-gray-500">~</span>
                <div class="relative">
                    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
                        <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd"></path></svg>
                    </div>
                    <input name="end" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full pl-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 " placeholder="Select date end">
                </div>
            </div>
            <div class="relative">
                <button type="submit" class=" lg:ml-5 md:ml-3 btn btn-light-primary">Submit</button>
            </div>  
        </div>
      </form>
    </div>
  </div>
  <div class="bg-white rounded-lg mt-6 p-6 space-y-12 lg:grid lg:grid-cols-3 lg:gap-x-6 lg:space-y-0">
    {% for cam in context.video_list %}
        {% for video in cam %}
        {% include "partials/list_box.html" with   camera=video.camera video=video.video thumbnail=video.thumbnail type=video.type datetime=video.datetime %}
        {% endfor %}    
    {% endfor %}
</div> 
  

  {% comment %} <div class="flex flex-col items-center justify-center mt-20 space-x-0 space-y-2 md:space-x-2 md:space-y-0 md:flex-row">
    <a href="#" class="w-full rounded-full btn btn-light btn-xl md:w-auto">Previous Page</a>
    <a href="#" class="w-full rounded-full btn btn-light btn-xl md:w-auto">Next Page</a>
  </div> {% endcomment %}
</section>

{% endblock content %}